ALTER TABLE ${SCHEMA_NAME}.vacancies
    ADD COLUMN IF NOT EXISTS public_language TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_about_the_job TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_responsibilities TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS public_responsibilities_heading TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_about_you TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_about_you_heading TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_profile TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS public_offers_intro TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_offers TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS public_offers_heading TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_quote TEXT NOT NULL DEFAULT '';
